name: Purge CDN Cache

on:
  push:
    branches:
      - main
      - beta

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache
        run: |
          # Main branch
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@main/blog-index.json
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@main/contributions.nix
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@main/data/
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@main/data/tr/
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@main/data/en/

          # Beta branch
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@beta/blog-index.json
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@beta/contributions.nix
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@beta/data/
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@beta/data/tr/
          curl -X POST https://purge.jsdelivr.net/gh/${{ github.repository }}@beta/data/en/
